## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    platform: org.hibernate.dialect.PostgresSQLDialect
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
#    generate-ddl: false
    hibernate:
      ddl-auto: ${create}
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM}
  #      dialect: org.hibernate.dialect.MySQL5Dialect

#  jackson:
#    default-property-inclusion: non_null
#  redis:
#    host: localhost
#    port: 6379
#  freemarker:
#      cache: false




  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    contextPath: /api

jwtSecret: me.zhulin
jwtExpiration: 86400

server: 
  port: ${PORT:8080}
